//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714jpoulin2h
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EZAutoModelContainer : DbContext
    {
        public EZAutoModelContainer()
            : base("name=EZAutoModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<RepairShop> RepairShops { get; set; }
        public virtual DbSet<PartStore> PartStores { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
    }
}
