//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714jpoulin2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartStore()
        {
            this.Reviews = new HashSet<Review>();
            this.Employee = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string PartStoreName { get; set; }
        public string PartStoreAddress { get; set; }
        public string PartStoreCity { get; set; }
        public string PartStoreState { get; set; }
        public string PartStoreZip { get; set; }
        public string PartStorePhone { get; set; }
        public string PartStoreEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Employee { get; set; }
    }
}
