//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714jpoulin2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int ReviewScore { get; set; }
        public string ReviewDescription { get; set; }
    
        public virtual RepairShop RepairShop { get; set; }
        public virtual PartStore PartStore { get; set; }
    }
}
